# Generated by Django 3.2 on 2021-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemspage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_type',
            field=models.CharField(choices=[('PP', 'Per Piece'), ('PK', 'Per Kilogram')], default='PP', max_length=2),
        ),
    ]
