# Generated by Django 3.2 on 2021-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemspage', '0002_item_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_type',
            field=models.CharField(choices=[('PP', 'per piece'), ('PK', 'per Kg')], default='PP', max_length=2),
        ),
    ]
