# Generated by Django 3.2 on 2021-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemspage', '0003_auto_20210603_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the description of the <django.db.models.fields.CharField>'),
        ),
    ]
