# Generated by Django 3.2 on 2021-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemspage', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the description for the <django.db.models.fields.CharField>'),
        ),
    ]
