# Generated by Django 3.2 on 2021-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemspage', '0005_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default='This is the description for the <django.db.models.fields.CharField>', max_length=1000),
        ),
    ]
